# Generated by Django 5.1.4 on 2025-01-01 05:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siwarkah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengambil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.IntegerField()),
                ('alamat', models.CharField(max_length=280)),
                ('tlp', models.CharField(max_length=13)),
                ('tgl', models.DateTimeField(default=datetime.datetime.today)),
                ('keterangan', models.CharField(max_length=280)),
                ('gambar', models.ImageField(null=True, upload_to='Foto_Pengambil/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik', models.CharField(max_length=100)),
                ('jenis', models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Hak Atas Tanah'), (2, 'Hak Tanggungan'), (3, 'Tanah Wakaf')])),
                ('nomor', models.CharField(max_length=5)),
                ('nib', models.CharField(max_length=5)),
                ('luas', models.IntegerField()),
                ('jns_bidang', models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Pekarangan'), (2, 'Pertanian'), (3, 'Perkebunan')])),
                ('tahun', models.IntegerField()),
                ('keterangan', models.CharField(max_length=280)),
                ('post', models.PositiveSmallIntegerField(default=0)),
                ('post_date', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(null=True)),
                ('pengambil_id', models.IntegerField(null=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.kelurahan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.user')),
            ],
        ),
    ]
