# Generated by Django 2.2.4 on 2019-10-01 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warkah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengambil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.IntegerField()),
                ('alamat', models.CharField(max_length=280)),
                ('tlp', models.CharField(max_length=13)),
                ('tgl', models.DateTimeField(default=datetime.datetime.today)),
                ('keterangan', models.CharField(max_length=280)),
                ('gambar', models.FileField(null=True, upload_to='Upload/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warkah.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik', models.CharField(max_length=100)),
                ('jenis', models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Hak Atas Tanah'), (2, 'Hak Tanggungan'), (3, 'Tanah Wakaf')])),
                ('nomor', models.CharField(max_length=5)),
                ('nib', models.CharField(max_length=5)),
                ('luas', models.IntegerField()),
                ('jns_bidang', models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Pekarangan'), (2, 'Pertanian'), (3, 'Lain-Lain')])),
                ('tahun', models.IntegerField()),
                ('keterangan', models.CharField(max_length=280)),
                ('post', models.PositiveSmallIntegerField(default=0)),
                ('post_date', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(null=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warkah.Kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warkah.Kelurahan')),
                ('pengambil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipekat.Pengambil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warkah.User')),
            ],
        ),
    ]
