# Generated by Django 2.2 on 2019-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipekat', '0002_remove_sertifikat_pengambil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifikat',
            name='pengambil_id',
            field=models.IntegerField(null=True),
        ),
    ]
