# Generated by Django 2.2.4 on 2019-10-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipekat', '0003_sertifikat_pengambil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengambil',
            name='gambar',
            field=models.ImageField(null=True, upload_to='Foto_Pengambil/'),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='jns_bidang',
            field=models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Pekarangan'), (2, 'Pertanian'), (3, 'Perkebunan')]),
        ),
    ]
