# Generated by Django 2.2.4 on 2019-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipekat', '0004_auto_20191010_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertifikat',
            name='jenis',
            field=models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Hak Tanggungan'), (2, 'Jual Beli'), (3, 'Pemecahan'), (4, 'Pendaftaran Hak 1X'), (5, 'Pengecekan'), (6, 'Pewarisan'), (7, 'Roya'), (8, 'Wakaf'), (9, 'Lain-Lain')]),
        ),
    ]
