# Generated by Django 2.2.4 on 2019-10-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipekat', '0005_auto_20191016_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sertifikat',
            old_name='nib',
            new_name='berkas',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='jns_bidang',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='luas',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='tahun',
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='jenis',
            field=models.PositiveSmallIntegerField(choices=[('', '---------'), (1, 'Hak Tanggungan'), (2, 'Jual Beli'), (3, 'Pemecahan'), (4, 'Pendaftaran SK Hak 1X'), (5, 'Pengecekan'), (6, 'Pewarisan'), (7, 'Roya'), (8, 'Wakaf'), (9, 'Lain-Lain')]),
        ),
    ]
